// GENERATED by @edgedb/generate v0.5.3

import type {Executor} from "edgedb";

export type GetPersonByNameArgs = {
  readonly "name": string;
};

export type GetPersonByNameReturns = Array<{
  "id": string;
  "name": string | null;
  "appears_in": Array<{
    "id": string;
    "title": string | null;
    "year": number | null;
    "@role": string | null;
  }>;
}>;

export function getPersonByName(client: Executor, args: GetPersonByNameArgs): Promise<GetPersonByNameReturns> {
  return client.query(`\
select Person { id, name, appears_in: { id, title, year, @role } } filter .name = <str>$name;`, args);

}
