// GENERATED by @edgedb/generate v0.5.3

import type {Executor} from "edgedb";

export type InsertMovieArgs = {
  readonly "title": string;
  readonly "year": number;
};

export type InsertMovieReturns = {
  "id": string;
};

export function insertMovie(client: Executor, args: InsertMovieArgs): Promise<InsertMovieReturns> {
  return client.queryRequiredSingle(`\
insert Movie { title := <str>$title, year := <int32>$year };`, args);

}
