// GENERATED by @edgedb/generate v0.5.3

import type {Executor} from "edgedb";

export type InsertPersonArgs = {
  readonly "name": string;
};

export type InsertPersonReturns = {
  "id": string;
};

export function insertPerson(client: Executor, args: InsertPersonArgs): Promise<InsertPersonReturns> {
  return client.queryRequiredSingle(`\
insert Person { name := <str>$name };`, args);

}
