// GENERATED by @edgedb/generate v0.5.3

import type {Executor} from "edgedb";

export type MovieAddCastArgs = {
  readonly "personName": string;
  readonly "role": string;
  readonly "title": string;
};

export type MovieAddCastReturns = Array<{
  "id": string;
}>;

export function movieAddCast(client: Executor, args: MovieAddCastArgs): Promise<MovieAddCastReturns> {
  return client.query(`\
update Movie filter .title = <str>$title set { casting += (select Person { @role := <str>$role } filter .name = <str>$personName) }`, args);

}
